### ISSUE TITLE
修复了GPT页面用户提问时输入html语言导致直接渲染的bug后出现新bug

### ISSUE THREAD

**Issue by aurora-wangq** [aurora-wangq/noel-refactored#1]
如图![bug](https://raw.githubusercontent.com/aurora-wangq/IMG/main/bug.png)

**Comment by aurora-wangq** [comment]
只在刷新后并且输入了html语言后触发

**Comment by MoveToEx** [comment]
![image](https://github.com/aurora-wangq/noel-refactored/assets/39954725/c4da19f5-99f5-4679-88cf-0ca7ec6b960f)
